#index:
#    path: /
#    controller: App\Controller\DefaultController::index
fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_area:
  resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
  prefix: /admin